### ISSUE TITLE
seed the local development database with employees so we have data to test our development application with

### ISSUE THREAD

**Issue by DylanSchroeder** [415-facewall/facewall-415#3]
Open your PostgreSQL shell, use the command CREATE DATABASE 415-facewall.
Create a new table in your database called employees.
Your employees table should include the data from the model.
Manually enter records for at least 6 employees (Dylan, Nathan, Craig, Marc, Keith, Jess) and 2 companies (DeltaV and NewBoCo) into your PostgreSQL tables from the PostgreSQL shell on your machine.

**Comment by tektechnologies** [comment]
The local and Remote Database have been populated with data.
